### ISSUE TITLE
optimize docs site for SEO & tracking

### ISSUE THREAD

**Issue by mrbar42** [Peer5/peer5-docs#22]
- [x] add Google analytics tracking
- [x] add SEO meta tags for all pages
- [x] add robots.txt & sitemap
- [x] add links to nimble, wowza etc to increase cross linking
- [x] add https support
